#!/usr/bin/env bash

set -e

pgcontents init -l $DATABASE_URL --no-prompt

#jupyter contrib nbextension install --user
#jupyter nbextensions_configurator enable --user

python3 -m notebook \
	--no-browser --no-mathjax --ip=* --port=$PORT \
	$JUPYTER_NOTEBOOK_ARGS
